version: '3'
services:
  app:
    build: .
    command: pipenv run server
    volumes:
      - .:/app:cached
    ports:
      - 7000:7000
    depends_on:
      - db
  db:
    image: postgres:11.1-alpine
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
