# Generated by Django 2.2.4 on 2019-08-12 12:28

from django.core.management import call_command
from django.db import migrations

# polls/fixtures/initial_data.jsonから取り込む
def load_fixture(apps, schema_editor):
    call_command('loaddata', 'initial_data', app_label='polls')

# すべて削除：ChoiceはQuestionから連鎖削除される
def unload_fixture(apps, schema_editor):
    MyModel = apps.get_model("polls", "Question")
    MyModel.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
